name: Generate Synthetic Data -> MongoDB Atlas

on:
  schedule:
    # 8:00 AM WAT (UTC+1) = 07:00 UTC
    - cron: "0 7 * * *"  # Runs at 07:00
    # 4:00 PM WAT (UTC+1) = 15:00 UTC
    - cron: "0 15 * * *"  # Runs at 15:00

    # Allows manual trigger or on-demand data generation.
  workflow_dispatch:

jobs:
  generate-data:
    name: Generate & Ingest Batch Data
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          pip install faker pymongo

      - name: Generate synthetic data to MongoDB Atlas
        run: |
          python -m generator.data_generator.py
        env:
          MONGO_URL: ${{ secrets.MONGO_URL }}
          MONGO_DB: ${{ secrets.MONGO_DB }}
          MONGO_COLLECTIONS: ${{ secrets.MONGO_COLLECTIONS }}
          ORDERS_MIN: ${{ secrets.ORDERS_MIN }}
          ORDERS_MAX: ${{ secrets.ORDERS_MAX }}
          CUSTOMERS_MIN: ${{ secrets.CUSTOMERS_MIN }}
          CUSTOMERS_MAX: ${{ secrets.CUSTOMERS_MAX }}
          PRODUCTS_MIN: ${{ secrets.PRODUCTS_MIN }}
          PRODUCTS_MAX: ${{ secrets.PRODUCTS_MAX }}
          PAYMENT_METHODS: ${{ secrets.PAYMENT_METHODS }}
          PAYMENT_STATUSES: ${{ secrets.PAYMENT_STATUSES }}
          PRODUCT_CATEGORIES: ${{ secrets.PRODUCT_CATEGORIES }}
          NUMBER_OF_BATCHES: ${{ secrets.NUMBER_OF_BATCHES }}

      - name: Log summary
        run: |
          echo "Data generated at $(date -u '+%Y-%m-%d %H:%M: UTC')"
          